### PR TITLE
fix UB introduced by llvm-9+

### LINKED ISSUE #412: bool evaluation UB introduced with llvm-9+
See this [comment](https://github.com/morganstanley/hobbes/blob/76bc9e4a3965eb5e5376495c23fc8f929416e707/test/Matching.C#L193)

llvm-9+ machine code instruction selection has  introduced a new assembly instruction negating bool values. I have not been able to track when this was introduced in LLVM, but @mo-xiaoming has recently demonstrated that this is definitely a broken behavior introduced by LLVM starting from version 9. He has filed a bug report to llvm-project, [here](https://bugs.llvm.org/show_bug.cgi?id=51163).

Until LLVM devs address the defect, let's patch our compilation in C++ by hand.

Evidence of UB and how the fix works can be found at [godbolt](https://godbolt.org/z/nWWT9jY63)

### PR DESCRIPTION
**Pull request by smunix**
fix #412 
ccls refactoring

### CODE REVIEW

File: include/hobbes/eval/cc.H [hunk 1]
```diff
@@ -84,175 +99,205 @@ public:
...
+        func<RFn>::arity == sizeof...(NamesAndExpr) - 1,
+        "Formal parameter list and expected function type arity mismatch");
+    return rcast<typename func<RFn>::type>(unsafeCompileFn(
+        lift<RFn>::type(*this), PArgl<NamesAndExpr...>::names(args...),
+        PArgl<NamesAndExpr...>::expr(
+            [&](const std::string &x) { return this->readExpr(x); }, args...)));
+  }
+
+  template <typename RFn, typename... NamesAndExpr>
+  boolSafeFn<RFn> compileSafeFn(NamesAndExpr &&...args) {
```
Comment (smunix) [inline include/hobbes/eval/cc.H:159]: @mo-xiaoming , @dawa79 - please help review this fix

Comment (smunix) [reply include/hobbes/eval/cc.H:159]: let's assess later (as a separate issue) what it would take to conflate `compileFn` and `compileSafeFn` into one single function

**Review by dawa79 — APPROVED** [review]

**Review by dawa79 — APPROVED** [review]

**Review by dawa79 — APPROVED** [review]

**Review by dawa79 — APPROVED** [review]
